# Generated by Django 4.0.4 on 2022-05-10 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('contact_number', models.CharField(max_length=100, verbose_name='Mobile Number')),
                ('email_id', models.EmailField(blank=True, max_length=254, verbose_name='Email ID')),
                ('driving_license_number', models.CharField(max_length=100, verbose_name='Driving License Number')),
            ],
            options={
                'verbose_name_plural': 'Customer Information',
            },
        ),
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=100, verbose_name='Locality')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.cities')),
            ],
            options={
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, unique=True, verbose_name='Business / Entity Name')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('mail_id', models.EmailField(max_length=100, verbose_name='Email ID')),
                ('whatsapp_number', models.CharField(max_length=100, verbose_name='Whatsapp Number')),
                ('account_number', models.CharField(max_length=100, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=100, verbose_name='IFSC Code')),
                ('upi_id', models.CharField(max_length=100, verbose_name='UPI ID')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.localities')),
            ],
            options={
                'verbose_name_plural': 'Partner Information',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_number', models.CharField(max_length=100, verbose_name='Vehicle / RC Number')),
                ('pricing', models.FloatField(verbose_name='Pricing Weekday')),
                ('partner_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.partnerinfo')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Details',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100, verbose_name='Payment Type')),
                ('payment_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Payment Date')),
                ('payment_reference', models.CharField(max_length=100, verbose_name='Payment Reference')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Pick Up Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('booking_status', models.CharField(choices=[('completed', 'Payment Completed'), ('picked', 'Picked Up'), ('returned', 'Returned')], default='Payment Complete', max_length=100, verbose_name='Booking Status')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('customer_information', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.customerinformation')),
                ('partner_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.partnerinfo')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.productdetails')),
            ],
            options={
                'verbose_name_plural': 'Transaction Details',
            },
        ),
    ]
