# Generated by Django 4.0.4 on 2022-04-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_number', models.CharField(max_length=100, verbose_name='Vehicle / RC Number')),
                ('pricing', models.FloatField(verbose_name='Pricing Weekday')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, unique=True, verbose_name='Business / Entity Name')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('mail_id', models.EmailField(max_length=100, verbose_name='Email ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('pincode', models.IntegerField(max_length=6, verbose_name='Pincode')),
                ('whatsapp_number', models.IntegerField(max_length=15, verbose_name='Whatsapp Number')),
                ('account_number', models.IntegerField(max_length=100, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=100, verbose_name='IFSC Code')),
                ('upi_id', models.CharField(max_length=100, verbose_name='UPI ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_number', models.CharField(max_length=100, verbose_name='Vehicle / RC Number')),
                ('pricing', models.FloatField(verbose_name='Pricing Weekday')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100, verbose_name='Payment Type')),
                ('payment_date', models.CharField(max_length=100, verbose_name='Payment Type')),
                ('payment_reference', models.CharField(max_length=100, verbose_name='Payment Reference')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('pickup_date', models.DateField(verbose_name='Pick Up Date')),
                ('return_date', models.DateField(verbose_name='Return Date')),
                ('booking_status', models.CharField(choices=[('completed', 'Payment Completed'), ('picked', 'Picked Up'), ('returned', 'Returned')], default='Payment Complete', max_length=100, verbose_name='Booking Status')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('customer_information', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.customerinformation')),
                ('partner_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.partnerinfo')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.productdetails')),
            ],
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.productcategory'),
        ),
    ]
