# Generated by Django 4.0.4 on 2022-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinformation',
            options={'verbose_name_plural': 'Customer Information'},
        ),
        migrations.AlterModelOptions(
            name='partnerinfo',
            options={'verbose_name_plural': 'Partner Information'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterModelOptions(
            name='transactiondetails',
            options={'verbose_name_plural': 'Transaction Details'},
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='rc_number',
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='contact_number',
            field=models.IntegerField(default=0, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='customer_name',
            field=models.CharField(default='', max_length=100, verbose_name='Customer Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='driving_license_number',
            field=models.CharField(default='', max_length=100, verbose_name='Driving License Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='email_id',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='partnerinfo',
            name='account_number',
            field=models.IntegerField(verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='partnerinfo',
            name='pincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='partnerinfo',
            name='whatsapp_number',
            field=models.IntegerField(verbose_name='Whatsapp Number'),
        ),
    ]
