# Generated by Django 4.0.4 on 2022-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0003_alter_customerinformation_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='pickup_date',
            field=models.DateField(null=True, verbose_name='Pick Up Date'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='return_date',
            field=models.DateField(null=True, verbose_name='Return Date'),
        ),
    ]
