# Generated by Django 4.0.4 on 2022-04-27 10:59

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0004_alter_transactiondetails_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinformation',
            name='email_id',
            field=models.EmailField(blank=True, default=datetime.now, max_length=254, verbose_name='Email ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='pickup_date',
            field=models.DateField(blank=True, default=datetime.now, verbose_name='Pick Up Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='return_date',
            field=models.DateField(blank=True, default=datetime.now, verbose_name='Return Date'),
            preserve_default=False,
        ),
    ]
