# Generated by Django 4.0.4 on 2022-05-15 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0005_alter_productdetails_available_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='pricing',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='deposit',
            field=models.FloatField(default=0, verbose_name='Deposit'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='pricing_weekday',
            field=models.FloatField(default=0, verbose_name='Pricing Weekday'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='pricing_weekend',
            field=models.FloatField(default=0, verbose_name='Pricing Weekend'),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Driving License Number'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 9, 22, 38, 560192)),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='booking_status',
            field=models.CharField(choices=[('started', 'Payment Started'), ('completed', 'Payment Completed'), ('picked', 'Picked Up'), ('returned', 'Returned')], default='Payment Started', max_length=100, verbose_name='Booking Status'),
        ),
    ]
