# Generated by Django 4.0.4 on 2022-05-15 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0006_remove_productdetails_pricing_productdetails_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 9, 34, 26, 362374)),
        ),
    ]
