# Generated by Django 4.0.4 on 2022-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0006_alter_transactiondetails_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinformation',
            name='contact_number',
            field=models.CharField(max_length=100, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='partnerinfo',
            name='account_number',
            field=models.CharField(max_length=100, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='partnerinfo',
            name='pincode',
            field=models.CharField(max_length=100, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='partnerinfo',
            name='whatsapp_number',
            field=models.CharField(max_length=100, verbose_name='Whatsapp Number'),
        ),
    ]
