# Generated by Django 4.0.4 on 2022-05-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0007_alter_customerinformation_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.RemoveField(
            model_name='partnerinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='partnerinfo',
            name='pincode',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='partner_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.partnerinfo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=100, verbose_name='Locality')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.cities')),
            ],
            options={
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.AddField(
            model_name='partnerinfo',
            name='locality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='lemiride_app_db.localities'),
            preserve_default=False,
        ),
    ]
