# Generated by Django 4.0.4 on 2022-05-15 11:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lemiride_app_db', '0013_alter_productdetails_available_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinformation',
            name='driving_license_number',
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='username',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 17, 10, 42, 557222)),
        ),
    ]
