# Generated by Django 4.0.4 on 2022-05-15 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0015_alter_customerinformation_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 17, 25, 24, 214926)),
        ),
    ]
