# Generated by Django 4.0.4 on 2022-05-16 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0020_alter_productdetails_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 9, 19, 732851)),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='booking_date',
            field=models.DateField(blank=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Reference'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payment Type'),
        ),
    ]
