# Generated by Django 4.0.4 on 2022-05-16 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0021_alter_productdetails_available_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='partner_info',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 16, 17, 25, 741569)),
        ),
    ]
