# Generated by Django 4.0.4 on 2022-05-16 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0022_remove_transactiondetails_partner_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 18, 0, 54, 320300)),
        ),
    ]
