# Generated by Django 4.0.4 on 2022-05-16 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0024_alter_productdetails_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 18, 8, 42, 679174)),
        ),
    ]
