# Generated by Django 4.0.4 on 2022-05-16 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0027_alter_productdetails_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 19, 44, 29, 82199)),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pick Up Date'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return Date'),
        ),
    ]
