# Generated by Django 4.0.4 on 2022-05-17 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemiride_app_db', '0029_alter_productdetails_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 19, 39, 23, 823674)),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
